* Ported to Barrier Breaker * Added Malta architecture on rgw, for qemu testing

diff --git a/patches/anyfi-mac/openwrt/01-add-wifi-hooks.patch b/patches/anyfi-mac/openwrt/01-add-wifi-hooks.patch
--- a/patches/anyfi-mac/openwrt/01-add-wifi-hooks.patch
+++ b/patches/anyfi-mac/openwrt/01-add-wifi-hooks.patch
@@ -18,14 +18,14 @@ Index: package/base-files/files/sbin/wifi
  		wifi_updown disable "$2"
 @@ -109,7 +116,9 @@
  		config_get iftype "$device" type
- 		if eval "type ${1}_$iftype" 2>/dev/null >/dev/null; then
- 			eval "scan_$iftype '$device'"
+		if eval "type ${1}_$iftype" 2>/dev/null >/dev/null; then
+			eval "scan_$iftype '$device'"
 +			[ "$1" = "disable" ] && run_hooks $device $DISABLE_HOOKS
- 			eval "${1}_$iftype '$device'" || echo "$device($iftype): ${1} failed"
+			eval "${1}_$iftype '$device'" || echo "$device($iftype): ${1} failed"
 +			[ "$1" = "enable" ] && run_hooks $device $ENABLE_HOOKS
- 		else
- 			echo "$device($iftype): Interface type not supported"
- 		fi
+		elif [ ! -f /lib/netifd/wireless/$iftype.sh ]; then
+			echo "$device($iftype): Interface type not supported"
+		fi
 @@ -193,6 +202,8 @@
  
  DEVICES=
